services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.2@sha256:639e019751642518a0fbdc2720e5f39789e76aa495a499852b9585ffacf71149
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file:
      - .env
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
      - keys:/config/keys
    ports:
      - 8120:8120

volumes:
  keys:
