services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.2.0@sha256:7fb1a4807d125ce036a17d37c940b4001402afcaf342a2c720c98d096b1b54da
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file:
      - .env
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
      - keys:/config/keys
    ports:
      - 8120:8120

volumes:
  keys:
