services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2.3.0@sha256:d5c1b59cad0875c4f08418bbfb465bf69694f3c37f97c6d036647477fbef729d
    container_name: komodo-periphery
    labels:
      komodo.skip:
    restart: unless-stopped
    env_file:
      - .env
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
      - keys:/config/keys
    ports:
      - 8120:8120

volumes:
  keys:
