services:
  app:
    image: ghcr.io/muety/wakapi:2.17.4@sha256:6fce764acf8775e1166e8b03e59fb6b34744e4a9fba5e98d9ea15d341db31bf8
    container_name: wakapi-app
    restart: unless-stopped
    ports:
      - 9008:3000
    env_file: .env

  db:
    image: postgres:17@sha256:39fb82e41109483c81ac15422a302500b4a753777b47f8431038703536bc6c52
    container_name: wakapi-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
