services:
  app:
    image: ghcr.io/muety/wakapi:2.17.5@sha256:b2ed3753af47c5adef330243c2431b04940f2560b57b9dba6029fd851a8f64a9
    container_name: wakapi-app
    restart: unless-stopped
    ports:
      - 9008:3000
    env_file: .env

  db:
    image: postgres:17@sha256:0b657ff48d7f76a1e907f381b1693eb4f2bf54c1d2df4feb6743d7dc601768dd
    container_name: wakapi-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
