services:
  app:
    image: ghcr.io/muety/wakapi:2.17.2@sha256:71dc015036efd760ad1a7a3e52a214847c6a601d2e0c5a70fb539a69c2d4d5d2
    container_name: wakapi-app
    restart: unless-stopped
    ports:
      - 9008:3000
    env_file: .env

  db:
    image: postgres:17@sha256:2cd82735a36356842d5eb1ef80db3ae8f1154172f0f653db48fde079b2a0b7f7
    container_name: wakapi-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
