services:
  app:
    image: yourls:1.10.6@sha256:8aab1ddd89e5f6b75e760a2d4fbbf6666e7fddca6242b8ed67c69e6730be6a86
    container_name: yourls-app
    restart: always
    depends_on:
      - db
    ports:
      - 9004:8080
    env_file:
      - .env

  db:
    image: mysql:9.7.2@sha256:e2bde46db6563855d7177adb5f0b57b9dc663f5a20927a90f4259d3312068497
    container_name: yourls-db
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
