services:
  app:
    image: yourls:1.10.4@sha256:7306f320dfde7c381ff3ec830d0a6dd677013643a6452ec0fc6ff6ce3ed923c8
    container_name: yourls-app
    restart: always
    depends_on:
      - db
    ports:
      - 9004:8080
    env_file:
      - .env

  db:
    image: mysql:9.7.1@sha256:ad88e1c86cbf12ef52d0a0360cd4b774d22956c5ee9c565645fb019d7aacb6c3
    container_name: yourls-db
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
