services:
  app:
    image: yourls:1.10.6@sha256:063ac7f8e04720a15b9fc949f3cf137330ffbf470fd43bcba123183d925649d1
    container_name: yourls-app
    restart: always
    depends_on:
      - db
    ports:
      - 9004:8080
    env_file:
      - .env

  db:
    image: mysql:26.7.0@sha256:66aec17cd21a956029b83f083b813073859e8355dc1a00e55df6ba02f0e32345
    container_name: yourls-db
    hostname: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
