services:
  app:
    image: shlinkio/shlink:stable
    container_name: shlink-app
    ports:
      - "9001:8080"
    env_file:
      - stack.env
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    container_name: shlink-db
    env_file:
      - stack.env
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
