services:
  app:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-app
    ports:
      - '9004:8080'
    volumes:
      - /etc/homelab/stirling/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /etc/homelab/stirling/extraConfigs:/configs
      - /etc/homelab/stirling/customFiles:/customFiles/
      - /etc/homelab/stirling/logs:/logs/
      - /etc/homelab/stirling/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB