services:
  app:
    image: stirlingtools/stirling-pdf:2.13.0-fat@sha256:c2face7b30f29ba751b22736d58d77685260dc2f8afe47484e95b2ec5a9de2d1
    container_name: stirling-app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -qv 'Please sign in'",
        ]
      interval: 5s
      timeout: 10s
      retries: 16
    restart: on-failure:5
    ports:
      - "9004:8080"
    volumes:
      - /etc/stirling/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /etc/stirling/extraConfigs:/configs
      - /etc/stirling/customFiles:/customFiles/
      - /etc/stirling/logs:/logs/
      - /etc/stirling/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
      - SECURITY_ENABLELOGIN=false
