services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.28.2@sha256:08b9411994c0d091c5cc0969ee9edcb85b5e79f26640703c0c342076ac6f2b17
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
