services:
  app:
    image: docker.n8n.io/n8nio/n8n:2.25.6@sha256:2996ce49af2b8dedc3d447ed1f5393ad15d11a1427a7460faa483027b2b61897
    container_name: n8n-app
    restart: unless-stopped
    ports:
      - "9001:5678"
    env_file:
      - .env
    volumes:
      - data:/home/node/.n8n
      - files:/files

volumes:
  data:
  files:
