services:
  app:
    container_name: home_assistant-app
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /etc/homelab/home_assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
