services:
  server:
    image: vaultwarden/server:1.36.0@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
    container_name: vaultwarden-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/data/
    ports:
      - 9012:80

volumes:
  data:
