services:
  server:
    image: vaultwarden/server:1.35.6@sha256:93072633c6b125628419097fc951d1ce448422a1af1d653805520a8ba90f6956
    container_name: vaultwarden-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/data/
    ports:
      - 9012:80

volumes:
  data:
