services:
  server:
    image: vaultwarden/server:1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
    container_name: vaultwarden-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/data/
    ports:
      - 9012:80

volumes:
  data:
