services:
  app:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono:latest@sha256:e98de08b458389df753d506db0ea0da48ff8323845ee094d643beb377fdcdd01
    container_name: checkmate-app
    pull_policy: always
    restart: always
    ports:
      - "9009:52345"
    env_file: .env
    depends_on:
      - db

  db:
    image: ghcr.io/bluewave-labs/checkmate-mongo:latest@sha256:c9026b4150f77aae3e1d3d47b077866f906776048a538b8d609058b13a0df415
    container_name: checkmate-db
    hostname: mongodb
    restart: always
    command: ["mongod", "--quiet", "--bind_ip_all"]
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  data:
