services:
  app:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono:latest@sha256:2b28595f6a4fce131fcbf3b6dc5b5a38d36f803f3183ccc4b5ae1870320c512e
    container_name: checkmate-app
    pull_policy: always
    restart: always
    ports:
      - "9009:52345"
    env_file: .env
    depends_on:
      - db

  db:
    image: ghcr.io/bluewave-labs/checkmate-mongo:latest@sha256:f6947013b737a96be73d22e5cfe61f0e4fdf38cb38652bf0b116257b74efbd94
    container_name: checkmate-db
    hostname: mongodb
    restart: always
    command: ["mongod", "--quiet", "--bind_ip_all"]
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  data:
