services:
  app:
    image: ghcr.io/bluewave-labs/checkmate-backend-mono:latest@sha256:fca87620e9c690f6d97ff6f92ab9cb1c44a69aa02edc7c8de48ecddd2748f622
    container_name: checkmate-app
    pull_policy: always
    restart: always
    ports:
      - "9009:52345"
    env_file: .env
    depends_on:
      - db

  db:
    image: ghcr.io/bluewave-labs/checkmate-mongo:latest@sha256:6f981761369184f32f007ea52ec5eab735c3494cebcb6a0b2882adaed06425b9
    container_name: checkmate-db
    hostname: mongodb
    restart: always
    command: ["mongod", "--quiet", "--bind_ip_all"]
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  data:
