services:
  app:
    image: ghcr.io/etechonomy/joplin-server:3.5.2@sha256:24d94c10548814ef72258b99598b28c5a9434791243338418514a9e7a81c63c6
    container_name: joplin-app
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    env_file:
      - stack.env

  db:
    image: postgres:18@sha256:bfe50b2b0ddd9b55eadedd066fe24c7c6fe06626185b73358c480ea37868024d
    container_name: joplin-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - stack.env

volumes:
  pg_data:
