services:
  app:
    image: ghcr.io/open-webui/open-webui:v0.11.0@sha256:72c0ba641ba75e7aa52655cb242570906ececd09b1140fb736483038a22b3228
    container_name: open_webui-app
    ports:
      - 9000:8080
    volumes:
      - data:/app/backend/data
    env_file:
      - .env
    restart: always

volumes:
  data:
