services:
  app:
    image: ghcr.io/open-webui/open-webui:v0.8.8@sha256:b478adc66210c1effe147d3e4a0d8845c0418b136ca14c314b9d83a087ad1c1f
    container_name: open_webui-app
    ports:
      - 9000:8080
    volumes:
      - data:/app/backend/data
    env_file:
      - .env
    restart: always

volumes:
  data:
