services:
  app:
    image: ghcr.io/open-webui/open-webui:v0.11.2@sha256:77ff490214a4b2699b309aa8d39bf4b42eca05f62d2742ef669ff846fcd10355
    container_name: open_webui-app
    ports:
      - 9000:8080
    volumes:
      - data:/app/backend/data
    env_file:
      - .env
    restart: always

volumes:
  data:
