services:
  app:
    image: ghcr.io/etechonomy/joplin-server:3.7.1@sha256:20a86045b5fa695ac9c5f4d3d99a026ef5c59cf89504b740d2010e3bae3300a2
    container_name: joplin-app
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:16@sha256:4b7183ac05f8ef417db21fd72d71047a4238340c261d3cc3ddb6d579ab5071ae
    container_name: joplin-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pg_data:
