services:
  app:
    image: ghcr.io/etechonomy/joplin-server:3.7.1@sha256:20a86045b5fa695ac9c5f4d3d99a026ef5c59cf89504b740d2010e3bae3300a2
    container_name: joplin-app
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:16@sha256:fe03a7605299a34ddf5e4f285dff78c3d7190a576b3c6b46f2fcff69f4bffd54
    container_name: joplin-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pg_data:
