services:
  app:
    image: ghcr.io/etechonomy/joplin-server:3.5.2@sha256:24d94c10548814ef72258b99598b28c5a9434791243338418514a9e7a81c63c6
    container_name: joplin-app
    depends_on:
      - db
    ports:
      - "22300:22300"
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:16@sha256:80dee66a0ba95a54d143008143e5d7ef628c0e8d5e0666b39d13c8bac3377953
    container_name: joplin-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pg_data:
