services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.75@sha256:50ac5916778faa06ad4adcff606c7aaf806cb55dc1995160dbf50633c9bda94d
    network_mode: host
    volumes:
      - /etc/adguard/work:/opt/adguardhome/work
      - /etc/adguard/conf:/opt/adguardhome/conf
    restart: always
