services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
    network_mode: host
    volumes:
      - /etc/adguard/work:/opt/adguardhome/work
      - /etc/adguard/conf:/opt/adguardhome/conf
    restart: always
