services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.74@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
    network_mode: host
    volumes:
      - /etc/adguard/work:/opt/adguardhome/work
      - /etc/adguard/conf:/opt/adguardhome/conf
    restart: always
